VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TRAIN: 6000
    POST_NMS_TOPK_TRAIN: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.005
  STEPS: (60000, 800000)
  MAX_ITER: 20000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
