_BASE_: "./base_rcnn.yaml"

INPUT:
  MASK_FORMAT: "bitmask"
MODEL:
  WEIGHTS: ""
  MASK_ON: True
  LOAD_PROPOSALS: False
  RESNETS:
    DEPTH: 50
  RETINANET:
    NUM_CLASSES: &num_classes 1
  ROI_HEADS:
    NUM_CLASSES: *num_classes
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  SEM_SEG_HEAD:
    NUM_CLASSES: *num_classes
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ("penn_fudan", )
  # TEST: ("penn_fudan_test", )
